# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "../", "/ircvpn"

  config.vm.provision "shell",
      inline: "apt-get update && apt-get -qqy install cmake build-essential libasio-dev libboost-log-dev ntp"
end
